[[gmmlib]]
arch = "i686"
git-tree-sha1 = "f409e635ebceb701ae816d0eff3e52cea4fd80ca"
libc = "glibc"
os = "linux"

    [[gmmlib.download]]
    sha256 = "dfa6c6da2936b12eecd9b3a607e904d6eb031f8366c8968aba9b0e5e7b25e4d2"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v20.3.2+0/gmmlib.v20.3.2.i686-linux-gnu.tar.gz"
[[gmmlib]]
arch = "i686"
git-tree-sha1 = "2b36d1919fd15bde78ae674522567fb1194304bf"
libc = "musl"
os = "linux"

    [[gmmlib.download]]
    sha256 = "6fbfc9297cdc069cd1bd02830b3c1d504fdcc8f7eeaa941481455e3d9bb3e35d"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v20.3.2+0/gmmlib.v20.3.2.i686-linux-musl.tar.gz"
[[gmmlib]]
arch = "x86_64"
git-tree-sha1 = "30198bfefe985c010a885a4137f439f33d317bb3"
libc = "glibc"
os = "linux"

    [[gmmlib.download]]
    sha256 = "c4a1f8330c001196705fc01f8e8caac840a2eb0e6e218420d9358089c15ca21b"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v20.3.2+0/gmmlib.v20.3.2.x86_64-linux-gnu.tar.gz"
[[gmmlib]]
arch = "x86_64"
git-tree-sha1 = "7c664188fc70cf805e2d1c03cb306bd128c31fc0"
libc = "musl"
os = "linux"

    [[gmmlib.download]]
    sha256 = "47768242d942c78d2d371e5b39efd8d11c15b03ec87c3f2f719503a0e1ce52ee"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v20.3.2+0/gmmlib.v20.3.2.x86_64-linux-musl.tar.gz"
