[[gmmlib]]
arch = "i686"
git-tree-sha1 = "78bd819a62405b433932ebacd0891d2b93fb70f9"
libc = "glibc"
os = "linux"

    [[gmmlib.download]]
    sha256 = "6eced4e9148916dba3f8b6ff5ce861723b527cde1cfd022a3ee2d40afe9b1dbf"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v22.3.19+0/gmmlib.v22.3.19.i686-linux-gnu.tar.gz"
[[gmmlib]]
arch = "i686"
git-tree-sha1 = "fc99a59cb2ff86b45782807630622e1f98adeb02"
libc = "musl"
os = "linux"

    [[gmmlib.download]]
    sha256 = "1613b3ea02f64d5fbc47274657adce832468e3863ca31173e5e63561a71d12db"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v22.3.19+0/gmmlib.v22.3.19.i686-linux-musl.tar.gz"
[[gmmlib]]
arch = "x86_64"
git-tree-sha1 = "c1b6ffe57a709cf69490b8d176019ac1a1bc0209"
libc = "glibc"
os = "linux"

    [[gmmlib.download]]
    sha256 = "3d184aa7589bb673f6585dbd08bdc9da9a0e9e3851e4347b65b18fd39f12f4f7"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v22.3.19+0/gmmlib.v22.3.19.x86_64-linux-gnu.tar.gz"
[[gmmlib]]
arch = "x86_64"
git-tree-sha1 = "97ff2608d04bd40c3b1ad6508b4d9c5a48c7d6d8"
libc = "musl"
os = "linux"

    [[gmmlib.download]]
    sha256 = "537f5cc144d683886a4803ff075b103b84fa1c7f397b44a04dd752b814b8a406"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v22.3.19+0/gmmlib.v22.3.19.x86_64-linux-musl.tar.gz"
