[[gmmlib]]
arch = "i686"
git-tree-sha1 = "12ec107e76d72e4ba608be8bbe12fa0b0f098fc9"
libc = "glibc"
os = "linux"

    [[gmmlib.download]]
    sha256 = "fd189c34d7f3b87942752603841a8ee2d074c55cd2886884e799537fcfeb0017"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v20.2.3+0/gmmlib.v20.2.3.i686-linux-gnu.tar.gz"
[[gmmlib]]
arch = "i686"
git-tree-sha1 = "4990ced1997f6bb0039e283fecdfd97c10d19072"
libc = "musl"
os = "linux"

    [[gmmlib.download]]
    sha256 = "aec02147636e7f58a96b6e8bf00956dfba7dd921e29585e056e2b9bc8d3e568b"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v20.2.3+0/gmmlib.v20.2.3.i686-linux-musl.tar.gz"
[[gmmlib]]
arch = "x86_64"
git-tree-sha1 = "70d70bc71c0817e05a4d347128cef822cd02d323"
libc = "glibc"
os = "linux"

    [[gmmlib.download]]
    sha256 = "137525001820acf0caa72b098a3cd6769c4c34f8b4f65ff46aa8bf78e5100bf0"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v20.2.3+0/gmmlib.v20.2.3.x86_64-linux-gnu.tar.gz"
[[gmmlib]]
arch = "x86_64"
git-tree-sha1 = "31d83236b31af44b1ce7d0f488efea7b9390028f"
libc = "musl"
os = "linux"

    [[gmmlib.download]]
    sha256 = "19e5aa77364adbfdbdafd995825c8e002c075307ef59e692068a336f5356ea5f"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v20.2.3+0/gmmlib.v20.2.3.x86_64-linux-musl.tar.gz"
