[[gmmlib]]
arch = "i686"
git-tree-sha1 = "7fa19170141d611fa698658d346f3efd3dcd6a40"
libc = "glibc"
os = "linux"

    [[gmmlib.download]]
    sha256 = "b31579c652f07fc8acbb967606028597e2fd304740c00c29723574d0cd928232"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v22.1.2+0/gmmlib.v22.1.2.i686-linux-gnu.tar.gz"
[[gmmlib]]
arch = "i686"
git-tree-sha1 = "3581c5cc6f4ede4e2ed4b70dde5c4a9873466d26"
libc = "musl"
os = "linux"

    [[gmmlib.download]]
    sha256 = "e97b3422c0e994c7373875cd0555eb30ed3aeba13a0b9b9d91fa25359da97fa3"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v22.1.2+0/gmmlib.v22.1.2.i686-linux-musl.tar.gz"
[[gmmlib]]
arch = "x86_64"
git-tree-sha1 = "e7e529656c00b2d9e670345a99a3ac69772a6b2c"
libc = "glibc"
os = "linux"

    [[gmmlib.download]]
    sha256 = "616e1914d7cef62029c05e3448381638cea14dff08db70823376fafc6b9a702f"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v22.1.2+0/gmmlib.v22.1.2.x86_64-linux-gnu.tar.gz"
[[gmmlib]]
arch = "x86_64"
git-tree-sha1 = "e2c24de02e2fdaf5319c4568eaf48ae9a051c7cd"
libc = "musl"
os = "linux"

    [[gmmlib.download]]
    sha256 = "14708f5bbf20f3609ca6587f0b862af4710c73c632328c5fe8646e8d1a12b559"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v22.1.2+0/gmmlib.v22.1.2.x86_64-linux-musl.tar.gz"
