[[gmmlib]]
arch = "i686"
git-tree-sha1 = "b520b9af33dbf33b1fed4896d31dd6a5dc86a231"
libc = "glibc"
os = "linux"

    [[gmmlib.download]]
    sha256 = "979ec4cc79353c019843d48829f1bdc741555990d99cce3e839a744797f9e5ee"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v20.2.4+0/gmmlib.v20.2.4.i686-linux-gnu.tar.gz"
[[gmmlib]]
arch = "i686"
git-tree-sha1 = "a762799991314949f85590e4c31eb9a2c4c73896"
libc = "musl"
os = "linux"

    [[gmmlib.download]]
    sha256 = "aa2c26ebbb0dd0a99d8ce90c4f37dc472810450b2b4d01de8fa69b37dcea4035"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v20.2.4+0/gmmlib.v20.2.4.i686-linux-musl.tar.gz"
[[gmmlib]]
arch = "x86_64"
git-tree-sha1 = "8a14bac92eca3b88117b0c12b1f4f9ff23df72ff"
libc = "glibc"
os = "linux"

    [[gmmlib.download]]
    sha256 = "fe2c99758693b69c5c122f14ebd331559851b19649406af6961d7aa296e14262"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v20.2.4+0/gmmlib.v20.2.4.x86_64-linux-gnu.tar.gz"
[[gmmlib]]
arch = "x86_64"
git-tree-sha1 = "d49063d26aee49740afde0233641f47feb92bac5"
libc = "musl"
os = "linux"

    [[gmmlib.download]]
    sha256 = "589f63a43c62ab50660f2fdec22461707a6e321b05a67b83ff620d5d8e7b3faa"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v20.2.4+0/gmmlib.v20.2.4.x86_64-linux-musl.tar.gz"
