[[gmmlib]]
arch = "i686"
git-tree-sha1 = "f30078df4fd26dfdf0f272ff7dc67a4a62f71e23"
libc = "glibc"
os = "linux"

    [[gmmlib.download]]
    sha256 = "77fa9bf607d380fcf67b1d0fd6cc6b47a663612bfb375107d7d7433943514d85"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v22.3.20+0/gmmlib.v22.3.20.i686-linux-gnu.tar.gz"
[[gmmlib]]
arch = "i686"
git-tree-sha1 = "013a3b6597b073a089d4eec25a50d689dff0061c"
libc = "musl"
os = "linux"

    [[gmmlib.download]]
    sha256 = "f0bc11cf05ece468d879a821d65b8266d2bc9a04be6374baa4bdb5fcbf31b3fb"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v22.3.20+0/gmmlib.v22.3.20.i686-linux-musl.tar.gz"
[[gmmlib]]
arch = "x86_64"
git-tree-sha1 = "83e2013570e9f30a0d1dac7e7daf0c1bf6b784e2"
libc = "glibc"
os = "linux"

    [[gmmlib.download]]
    sha256 = "b9926d45a674a51686f36b61c29e5fe0624075eb5e482850af054041eb537478"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v22.3.20+0/gmmlib.v22.3.20.x86_64-linux-gnu.tar.gz"
[[gmmlib]]
arch = "x86_64"
git-tree-sha1 = "1661f79963d1bbb096752b3369fb05e7504892fc"
libc = "musl"
os = "linux"

    [[gmmlib.download]]
    sha256 = "7585b78f76ff258181ea2ded68d653a7806731e96c13a5f195dfcf2bdbdc2b0c"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v22.3.20+0/gmmlib.v22.3.20.x86_64-linux-musl.tar.gz"
