[[gmmlib]]
arch = "i686"
git-tree-sha1 = "13c4ce3ee19a3d03dbeb44ed556f2e21ee865691"
libc = "glibc"
os = "linux"

    [[gmmlib.download]]
    sha256 = "15e6309f6d49cfe3aa70bffd0327a12ae608b193f0568fff67cbc766f2ebbf43"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v20.2.2+0/gmmlib.v20.2.2.i686-linux-gnu.tar.gz"
[[gmmlib]]
arch = "i686"
git-tree-sha1 = "694fcf8bba6e2011730ca8734189dfe353e561b2"
libc = "musl"
os = "linux"

    [[gmmlib.download]]
    sha256 = "5b6bd07823ed54ff9326e7337f970bdfee154c15d6b126f120951fc5a701c541"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v20.2.2+0/gmmlib.v20.2.2.i686-linux-musl.tar.gz"
[[gmmlib]]
arch = "x86_64"
git-tree-sha1 = "5713593d581079904d8ed121c15a0fc90fb3a14e"
libc = "glibc"
os = "linux"

    [[gmmlib.download]]
    sha256 = "6c8b43362068e0e2572d4f73d7e6872bfb1a78423f19a41ecbd0ce7964c23664"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v20.2.2+0/gmmlib.v20.2.2.x86_64-linux-gnu.tar.gz"
[[gmmlib]]
arch = "x86_64"
git-tree-sha1 = "abee02a2a6d5edbe2809d62b4ca4669fa9fed583"
libc = "musl"
os = "linux"

    [[gmmlib.download]]
    sha256 = "118fe278e0a60a61f1755188b0210a7d5cc9d7bc5c2677a9c476a83da428eba4"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v20.2.2+0/gmmlib.v20.2.2.x86_64-linux-musl.tar.gz"
