[[gmmlib]]
arch = "i686"
git-tree-sha1 = "ced0ce98ba99deefbed0fee02b57471c611e8278"
libc = "glibc"
os = "linux"

    [[gmmlib.download]]
    sha256 = "1b7c145f8ebb49d0c41713fa02613e87d650f91b6bc1597f98f8632d9f589a4c"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v20.2.5+0/gmmlib.v20.2.5.i686-linux-gnu.tar.gz"
[[gmmlib]]
arch = "i686"
git-tree-sha1 = "4e37b6ef59538b4b77c95f787ffeb701daa919e7"
libc = "musl"
os = "linux"

    [[gmmlib.download]]
    sha256 = "d9a665cc19a15a6fa8eb5df7422639fb3019d9a95e9a24ae959cb42a2f08688a"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v20.2.5+0/gmmlib.v20.2.5.i686-linux-musl.tar.gz"
[[gmmlib]]
arch = "x86_64"
git-tree-sha1 = "d4a0c3912ef71bf8bd0ea4a699a0e7acf0f0aab1"
libc = "glibc"
os = "linux"

    [[gmmlib.download]]
    sha256 = "0bb3ed65ade097c26dc991e6b459546e143f972fcd6ebe9b0946e55ab2bc6fca"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v20.2.5+0/gmmlib.v20.2.5.x86_64-linux-gnu.tar.gz"
[[gmmlib]]
arch = "x86_64"
git-tree-sha1 = "a79c30bbcf6eb19bc3deb253a9b61f2f64f75ebf"
libc = "musl"
os = "linux"

    [[gmmlib.download]]
    sha256 = "14af5642b257c0fe60f1b08b918fc48e088044bf5013e76fce4384f1af978e8b"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v20.2.5+0/gmmlib.v20.2.5.x86_64-linux-musl.tar.gz"
