[[gmmlib]]
arch = "i686"
git-tree-sha1 = "c9bb788a969415e867ff15e37e0e5b88dd9b27bb"
libc = "glibc"
os = "linux"

    [[gmmlib.download]]
    sha256 = "97d565f41d102b472b808cbcb02d98c97f2a6ca448f4637baac8f881b821d7ba"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v22.1.3+0/gmmlib.v22.1.3.i686-linux-gnu.tar.gz"
[[gmmlib]]
arch = "i686"
git-tree-sha1 = "829fcb0a833604133d801f575bf7e6256ffd4759"
libc = "musl"
os = "linux"

    [[gmmlib.download]]
    sha256 = "113ff47b3dfd266d61640321a85cce53406577b78621d89799bcbec74f69dabf"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v22.1.3+0/gmmlib.v22.1.3.i686-linux-musl.tar.gz"
[[gmmlib]]
arch = "x86_64"
git-tree-sha1 = "f584bfd28a12cf19a19e5d54a5b80f2fbfd3a5cd"
libc = "glibc"
os = "linux"

    [[gmmlib.download]]
    sha256 = "2a4836cb4e1df3eb80fdbf29cfbeaaab241b2efe6c3b0f9692e3330d3db5ea9c"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v22.1.3+0/gmmlib.v22.1.3.x86_64-linux-gnu.tar.gz"
[[gmmlib]]
arch = "x86_64"
git-tree-sha1 = "1ca07e488a9fa463eb14f4a9f09954abd632a18e"
libc = "musl"
os = "linux"

    [[gmmlib.download]]
    sha256 = "c4c0bc13d656d5a653eb8040be22baa93f2b87bfff89c1355705d27246a7405e"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v22.1.3+0/gmmlib.v22.1.3.x86_64-linux-musl.tar.gz"
