[[gmmlib]]
arch = "i686"
git-tree-sha1 = "2decc79b3380742daccfd3253bb80971488e8532"
libc = "musl"
os = "linux"

    [[gmmlib.download]]
    sha256 = "0f14fb55796c64ba9f90f7d0630f73772166834f19420fee275dcb25dae6b204"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v20.1.1+3/gmmlib.v20.1.1.i686-linux-musl.tar.gz"
[[gmmlib]]
arch = "i686"
git-tree-sha1 = "6b8f9e66d3f50f14ced4c41ed909bcca5bc41de9"
libc = "glibc"
os = "linux"

    [[gmmlib.download]]
    sha256 = "3a927cb6b8542ced2d4a04ad4a973325969e3295de62a5e7638da60104d1e015"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v20.1.1+3/gmmlib.v20.1.1.i686-linux-gnu.tar.gz"
[[gmmlib]]
arch = "x86_64"
git-tree-sha1 = "c4e3b1f78fc7e67c65c9419b6f8c4aa496659ed9"
libc = "musl"
os = "linux"

    [[gmmlib.download]]
    sha256 = "3d92627d29f33a542192f580601c894983d2f6a78f3201d9c6d79a2adb7b9745"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v20.1.1+3/gmmlib.v20.1.1.x86_64-linux-musl.tar.gz"
[[gmmlib]]
arch = "x86_64"
git-tree-sha1 = "80556e4d924535136a29db65462df002535c9af1"
libc = "glibc"
os = "linux"

    [[gmmlib.download]]
    sha256 = "e5e71e1c44eab7a5d91b56f1e453f8d21e0cab346a1100cc2aff2fc256974992"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v20.1.1+3/gmmlib.v20.1.1.x86_64-linux-gnu.tar.gz"
