[[gmmlib]]
arch = "i686"
git-tree-sha1 = "4304a9dde5e1535f6aaa480c4ce47ec4bd7dc80f"
libc = "glibc"
os = "linux"

    [[gmmlib.download]]
    sha256 = "fe07affe918ee1401b2a1c136ef8b7aace3d286fe35384a5c0f4a0c6e7dc2a7b"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v19.4.1+0/gmmlib.v19.4.1.i686-linux-gnu.tar.gz"
[[gmmlib]]
arch = "x86_64"
git-tree-sha1 = "fe37248dea9fe055a4eae6b12816af2b1ef7de99"
libc = "glibc"
os = "linux"

    [[gmmlib.download]]
    sha256 = "4dc9d82a24cc53ffe80a066a673463976df8a6f287e1ee830b1a1de72e8c9f4f"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v19.4.1+0/gmmlib.v19.4.1.x86_64-linux-gnu.tar.gz"
