[[gmmlib]]
arch = "i686"
git-tree-sha1 = "e3b5d9f917cc8a6311db619a07714a8a043891b7"
libc = "glibc"
os = "linux"

    [[gmmlib.download]]
    sha256 = "eba380287e9c8fec919e008b5f2ce93acaadffd1d9f8d69ddd3d4b4d509f8121"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v22.8.1+0/gmmlib.v22.8.1.i686-linux-gnu.tar.gz"
[[gmmlib]]
arch = "i686"
git-tree-sha1 = "dbe72de802e23613ea22a989a13b5c2327b72907"
libc = "musl"
os = "linux"

    [[gmmlib.download]]
    sha256 = "0d9337e0a206770158c7dff21d518e3b82fa451f858141b5837d747988432c1b"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v22.8.1+0/gmmlib.v22.8.1.i686-linux-musl.tar.gz"
[[gmmlib]]
arch = "x86_64"
git-tree-sha1 = "38e5a4cd58eabae719b829561afe10d001b30363"
libc = "glibc"
os = "linux"

    [[gmmlib.download]]
    sha256 = "909e050912dfbc4567988d726b47f5c9aa95c2765666ef989f6a8694fa052548"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v22.8.1+0/gmmlib.v22.8.1.x86_64-linux-gnu.tar.gz"
[[gmmlib]]
arch = "x86_64"
git-tree-sha1 = "b3a50bed7c7fd1d0763ec5bee62875384685b1d8"
libc = "musl"
os = "linux"

    [[gmmlib.download]]
    sha256 = "7ff26dad72d211125aca0a26d2b4690e0f1394ac2bd8f8b138a67e72abe1cb35"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v22.8.1+0/gmmlib.v22.8.1.x86_64-linux-musl.tar.gz"
