[[gmmlib]]
arch = "i686"
git-tree-sha1 = "a1234206f23f00e0e41eae2d61487443a2f61850"
libc = "glibc"
os = "linux"

    [[gmmlib.download]]
    sha256 = "919f6d6fb562711afc97baf883433df88587cf43c3ddd94767da1673260f3c5f"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v22.3.0+0/gmmlib.v22.3.0.i686-linux-gnu.tar.gz"
[[gmmlib]]
arch = "i686"
git-tree-sha1 = "5c6a0cddd9488f5c491b2ff549512ff2d78291ee"
libc = "musl"
os = "linux"

    [[gmmlib.download]]
    sha256 = "4a03cc05d2775ec8483cc53ccff841781096c432ba890f702454c02f86bb9551"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v22.3.0+0/gmmlib.v22.3.0.i686-linux-musl.tar.gz"
[[gmmlib]]
arch = "x86_64"
git-tree-sha1 = "1f40b0339fed28c5bfe799d8dc1234a358876ace"
libc = "glibc"
os = "linux"

    [[gmmlib.download]]
    sha256 = "9491d501c165fad2eedf33e305d3356fc8bc351e007366eed051a2b641bee521"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v22.3.0+0/gmmlib.v22.3.0.x86_64-linux-gnu.tar.gz"
[[gmmlib]]
arch = "x86_64"
git-tree-sha1 = "cf97bc4957b304aa8994de8f96b8f885081dfe28"
libc = "musl"
os = "linux"

    [[gmmlib.download]]
    sha256 = "b7584275d3484c14660a48701db708caefcdd63b228f9ccf1eea8b1fa64f9478"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v22.3.0+0/gmmlib.v22.3.0.x86_64-linux-musl.tar.gz"
