[[gmmlib]]
arch = "i686"
git-tree-sha1 = "4cf27ba6b0a4b6b6ef9406c0f9061ab3d4eb7099"
libc = "glibc"
os = "linux"

    [[gmmlib.download]]
    sha256 = "8122ed8b681b336aea58a51df15b40cbea1b320a2ba7ae1eeef1fc667edd9279"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v22.3.17+0/gmmlib.v22.3.17.i686-linux-gnu.tar.gz"
[[gmmlib]]
arch = "i686"
git-tree-sha1 = "e7e1c17820f7faea2bb684f2438873d5116f0a76"
libc = "musl"
os = "linux"

    [[gmmlib.download]]
    sha256 = "674cc359db14fc75cb5e9922173574084fb6476c48292c6322afecb4d7e78a6e"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v22.3.17+0/gmmlib.v22.3.17.i686-linux-musl.tar.gz"
[[gmmlib]]
arch = "x86_64"
git-tree-sha1 = "be9d1cd776269d571d16522f35ed5c6af4309a4b"
libc = "glibc"
os = "linux"

    [[gmmlib.download]]
    sha256 = "339fc44e8fe1a04b60a33d8087357e3a67387e6b716de70988e92538310895e9"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v22.3.17+0/gmmlib.v22.3.17.x86_64-linux-gnu.tar.gz"
[[gmmlib]]
arch = "x86_64"
git-tree-sha1 = "c0101e715233784278368add090bcff07e6d1e04"
libc = "musl"
os = "linux"

    [[gmmlib.download]]
    sha256 = "e8d9bcad4f52ba7aa66344783ce22354d8725cb6939ae9856817d317138bfc8e"
    url = "https://github.com/JuliaBinaryWrappers/gmmlib_jll.jl/releases/download/gmmlib-v22.3.17+0/gmmlib.v22.3.17.x86_64-linux-musl.tar.gz"
